### GET request to example server
GET http://localhost:8080/books

###
GET http://localhost:8080/books/5

###
GET http://localhost:8080/books/3

###
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "IELTS 8",
  "isbn": "isbn-4",
  "price": 23
}

###
PUT http://localhost:8080/books/2
Content-Type: application/json

{
  "title": "Java 8 in Action (updated)",
  "isbn": "isbn-2",
  "price": 38
}

###
DELETE http://localhost:8080/books/5

###
DELETE http://localhost:8080/books/3